name: fluintl
description: A Flutter Internationalization support package.Use it to quickly build an international Apps.
version: 2.0.0
homepage: https://github.com/Sky24n/fluintl

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter